version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www/public:/var/www/html/
            - ./www/api:/var/www/html/api/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:latest
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
            - ./mysql-init:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
volumes:
    persistent:
