<?php
	// PATHS
	$USERIMAGEPATH = "uploads/userimages";
	
	// ERROR CODES
	$ERROR_PAGE_NOT_FOUND = 404;
	$ERROR_PERMISSION_DENIED = 403;
	
	// SUCCESS CODES
	$CODE_NOT_LOGGED_IN = -1;
	$CODE_ERROR = 0;
	$CODE_SUCCESS = 1;
	$CODE_ALREADY_APPROVED = 2;
	$CODE_INSUFFICIENT_PARAMETERS = 3;
	$CODE_USER_ALREADY_EXISTS = 4;
	$CODE_PERMISSION_DENIED = 5;
	$CODE_MALFORMED = 6;
	$CODE_NOT_FOUND = 7;
?>